@startuml
left to right direction
actor User as user

rectangle ChatClient {
  usecase "Register" as UC1
  usecase "List other clients" as UC2
  usecase "Send message" as UC3
  usecase "Check incoming messages" as UC4
  usecase "Quit" as UC6

  UC1 --> UC2
  UC2 --> UC3
  UC3 --> UC4
  UC4 --> UC6

  user --> UC1
  user --> UC2
  user --> UC3
  user --> UC4
  user --> UC6
}

rectangle ChatServer {
  usecase "Accept connections" as UC7
  usecase "Listen for messages" as UC8
  usecase "Send messages" as UC9
  usecase "Handle disconnections" as UC10
  usecase "Shutdown" as UC11

  UC7 --> UC8
  UC8 --> UC9
  UC9 --> UC8
  UC8 --> UC10
  UC10 --> UC8
  UC11 --> UC10
}

ChatClient --> ChatServer: Send/Receive messages
ChatServer --> ChatClient: Send/Receive messages
ChatServer --> UC7
@enduml
